In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
!git clone https://github.com/laureneproctor/Olympiad-AI.git
%cd /content/Olympiad-AI

Cloning into 'Olympiad-AI'...
remote: Enumerating objects: 1476, done.
remote: Counting objects: 100% (245/245), done.
remote: Compressing objects: 100% (233/233), done.
remote: Total 1476 (delta 160), reused 11 (delta 11), pack-reused 1231 (from 3)
Receiving objects: 100% (1476/1476), 1.59 MiB | 28.51 MiB/s, done.
Resolving deltas: 100% (880/880), done.
/content/Olympiad-AI

In [3]:
!pip -q install -U \
  transformers \
  datasets \
  peft \
  trl \
  accelerate \
  bitsandbytes \
  pyyaml \
  sentencepiece

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 147.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 527.0/527.0 kB 60.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 630.8/630.8 kB 82.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 42.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.6/47.6 MB 57.9 MB/s eta 0:00:00

In [4]:
from aimo3.scripts.grpo import train_grpo
train_grpo("aimo3/configs/grpo_deepseekmath_exp1.yaml")

Experiment: exp1
Model key: deepseekmath
Base model: deepseek-ai/deepseek-math-7b-instruct
Starting checkpoint: /content/drive/MyDrive/Math Olympiad Competition/Experimentation/models/sft_deepseekmath_exp1
RL train path: /content/drive/MyDrive/Math Olympiad Competition/Experimentation/rl_train/mined_deepseekmath_exp1_50000
Output directory: /content/drive/MyDrive/Math Olympiad Competition/Experimentation/models/grpo_deepseekmath_exp1
Loading RL dataset from: /content/drive/MyDrive/Math Olympiad Competition/Experimentation/rl_train/mined_deepseekmath_exp1_50000
RL train rows: 106
Columns: ['prompt', 'expected_answer', 'problem', 'majority_answer', 'agreement', 'format_validity_rate', 'n_valid_extractions', 'vote_counts', 'mine_reasons']
Formatting RL dataset
Formatted columns: ['prompt', 'expected_answer', 'problem', 'majority_answer', 'agreement', 'format_validity_rate', 'n_valid_extractions', 'vote_counts', 'mine_reasons']

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/594 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

pytorch_model.bin.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Loading weights:   0%|          | 0/273 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/121 [00:00<?, ?B/s]

Loading weights:   0%|          | 0/421 [00:00<?, ?it/s]

LlamaForCausalLM LOAD REPORT from: /content/drive/MyDrive/Math Olympiad Competition/Experimentation/models/sft_deepseekmath_exp1
Key                             | Status     |
--------------------------------+------------+---------------------------------------------------------------------------------------------------
base_model.model.lm_head.weight | UNEXPECTED |
model.embed_tokens.weight       | MISMATCH   | Reinit due to size mismatch - ckpt: torch.Size([100002, 4096]) vs model:torch.Size([102400, 4096])

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISMATCH:	ckpt weights were loaded, but they did not match the original empty weight shapes.

Warning: checkpoint load had shape mismatches. Retrying with ignore_mismatched_sizes=True.

Loading weights:   0%|          | 0/273 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/421 [00:00<?, ?it/s]

LlamaForCausalLM LOAD REPORT from: /content/drive/MyDrive/Math Olympiad Competition/Experimentation/models/sft_deepseekmath_exp1
Key                             | Status     |
--------------------------------+------------+---------------------------------------------------------------------------------------------------
base_model.model.lm_head.weight | UNEXPECTED |
model.embed_tokens.weight       | MISMATCH   | Reinit due to size mismatch - ckpt: torch.Size([100002, 4096]) vs model:torch.Size([102400, 4096])

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISMATCH:	ckpt weights were loaded, but they did not match the original empty weight shapes.

Note: dropped unsupported GRPOConfig params for this TRL version: {'max_prompt_length'}

/usr/local/lib/python3.12/dist-packages/peft/mapping_func.py:72: UserWarning: You are trying to modify a model with PEFT for a second time. If you want to reload the model with a different config, make sure to call `.unload()` before.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/peft/tuners/tuners_utils.py:285: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'pad_token_id': 100001}.

Starting GRPO training

Saving GRPO model + tokenizer
Done. Saved to: /content/drive/MyDrive/Math Olympiad Competition/Experimentation/models/grpo_deepseekmath_exp1

In [5]:
from aimo3.scripts.grpo import train_grpo
train_grpo("aimo3/configs/grpo_deepseekmath_exp3.yaml")

Experiment: exp3
Model key: deepseekmath
Base model: deepseek-ai/deepseek-math-7b-instruct
Starting checkpoint: /content/drive/MyDrive/Math Olympiad Competition/Experimentation/models/sft_deepseekmath_exp3
RL train path: /content/drive/MyDrive/Math Olympiad Competition/Experimentation/rl_train/mined_deepseekmath_exp3_50000
Output directory: /content/drive/MyDrive/Math Olympiad Competition/Experimentation/models/grpo_deepseekmath_exp3
Loading RL dataset from: /content/drive/MyDrive/Math Olympiad Competition/Experimentation/rl_train/mined_deepseekmath_exp3_50000
RL train rows: 133
Columns: ['prompt', 'expected_answer', 'problem', 'majority_answer', 'agreement', 'format_validity_rate', 'n_valid_extractions', 'vote_counts', 'mine_reasons']
Formatting RL dataset

Formatting RL dataset:   0%|          | 0/133 [00:00<?, ? examples/s]

Formatted columns: ['prompt', 'expected_answer', 'problem', 'majority_answer', 'agreement', 'format_validity_rate', 'n_valid_extractions', 'vote_counts', 'mine_reasons']

Loading weights:   0%|          | 0/273 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/421 [00:00<?, ?it/s]

LlamaForCausalLM LOAD REPORT from: /content/drive/MyDrive/Math Olympiad Competition/Experimentation/models/sft_deepseekmath_exp3
Key                             | Status     |
--------------------------------+------------+---------------------------------------------------------------------------------------------------
base_model.model.lm_head.weight | UNEXPECTED |
model.embed_tokens.weight       | MISMATCH   | Reinit due to size mismatch - ckpt: torch.Size([100002, 4096]) vs model:torch.Size([102400, 4096])

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISMATCH:	ckpt weights were loaded, but they did not match the original empty weight shapes.

Warning: checkpoint load had shape mismatches. Retrying with ignore_mismatched_sizes=True.

Loading weights:   0%|          | 0/273 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/421 [00:00<?, ?it/s]

LlamaForCausalLM LOAD REPORT from: /content/drive/MyDrive/Math Olympiad Competition/Experimentation/models/sft_deepseekmath_exp3
Key                             | Status     |
--------------------------------+------------+---------------------------------------------------------------------------------------------------
base_model.model.lm_head.weight | UNEXPECTED |
model.embed_tokens.weight       | MISMATCH   | Reinit due to size mismatch - ckpt: torch.Size([100002, 4096]) vs model:torch.Size([102400, 4096])

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISMATCH:	ckpt weights were loaded, but they did not match the original empty weight shapes.

Note: dropped unsupported GRPOConfig params for this TRL version: {'max_prompt_length'}

/usr/local/lib/python3.12/dist-packages/peft/mapping_func.py:72: UserWarning: You are trying to modify a model with PEFT for a second time. If you want to reload the model with a different config, make sure to call `.unload()` before.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/peft/tuners/tuners_utils.py:285: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'pad_token_id': 100001}.

Starting GRPO training

Saving GRPO model + tokenizer
Done. Saved to: /content/drive/MyDrive/Math Olympiad Competition/Experimentation/models/grpo_deepseekmath_exp3